Auto works firsttry
kennedyrobotics1/IntoTheDeep24-25 pull request #19
Opened 2024-12-19 03:29 UTC by AkithMadurapperuma

Working 1 high bar specimen and then park auto. It also has the classes for each subsystem action and classes that we can use to test individual subsystem's auto.

2024-12-21 02:53 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +        rightBack.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
what this for

2024-12-21 02:53 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +// multiply by 360 to convert it to 0 to 360 degrees
we're not going to use axon encoders at this point so I don't think we need this anymore

2025-01-07 01:06 UTC, CubeOfCheese requested changes

2025-01-07 01:06 UTC, CubeOfCheese commented on MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
> +<<<<<<< HEAD
I can't believe you committed merge markers

2025-01-07 01:35 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousTracker.java
>      public AutonomousTracker(double newx, double newy, double newr) {
i thought we weren't using the auto tracker files anymore?

2025-01-07 01:36 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/goBuildaTestingTeleop.java
> +//package org.firstinspires.ftc.teamcode.Teleop;
???

2025-01-07 01:36 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +        rightBack.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
didnt need this, destroyed/dismantled/demolished this code.

2025-01-07 01:36 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +// multiply by 360 to convert it to 0 to 360 degrees
didnt need this, destroyed/dismantled/demolished this code.

2025-01-07 01:37 UTC, AkithMadurapperuma commented on MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
> +<<<<<<< HEAD
Extremley sorry, dont know what was wrong with me when I added these lines, wont happen again. Sri Lanka!

2025-01-07 01:37 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/IntakeSpecimen.java
> +package org.firstinspires.ftc.teamcode.Autonomous;
did we ever test this?

2025-01-07 01:38 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +                ),
do these actions together work at theses steps or were they ever tested?

2025-01-07 01:38 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/AutonomousTracker.java
>      public AutonomousTracker(double newx, double newy, double newr) {
You are completely and utterly correct on this. Thanks for catching this terrible mistake I made. Sri Lanka!

2025-01-07 01:38 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/IntakeSpecimen.java
> +//wrist.pickUpSpecimenFromHumanPlayer()
What is this?

2025-01-07 01:38 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +    private AnalogInput armLeftFrontEncoder;
I don't want to use analog from the axons

2025-01-07 01:39 UTC, CubeOfCheese commented on MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
> +<<<<<<< HEAD
![OlympicOlympicsGIF](https://github.com/user-attachments/assets/2064c2d9-dc24-44b2-b380-10e16c03603b)

2025-01-07 01:40 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/goBuildaTestingTeleop.java
> +//package org.firstinspires.ftc.teamcode.Teleop;
Deleted this, once again, I express my deepest and sincerest apologies to this mistake I made. Sri Lanka!

2025-01-07 01:42 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/IntakeSpecimen.java
> +package org.firstinspires.ftc.teamcode.Autonomous;
Dont know what come over me when I did this. Truly, im sorry. Sri Lanka!

2025-01-07 01:54 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +                ),
These actions were tested on our first variation of the bot, it failed, still added them to a new branch and deleted off of this one.

2025-01-07 01:54 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/IntakeSpecimen.java
> +//wrist.pickUpSpecimenFromHumanPlayer()
Deleted whole file, didnt need it.

2025-01-07 01:54 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +    private AnalogInput armLeftFrontEncoder;
Deleted

2025-01-09 00:06 UTC, atra-ment approved these changes

2025-01-09 00:06 UTC, isabellammjfk approved these changes
goods sick man
buen trabajo

2025-01-09 00:06 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +        }
y this here it doesn't do anything

2025-01-09 00:06 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +                )
delete

2025-01-09 00:07 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +                ),
Why is this a parallel action

2025-01-09 00:08 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +            armPosition.update(-0.008);
no thx

2025-01-09 00:09 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +                ),
FIXED
![images](https://github.com/user-attachments/assets/b23839f3-b446-40de-8e84-457177af8c24)

2025-01-09 00:10 UTC, AkithMadurapperuma commented
> goods sick man buen trabajo

2025-01-09 00:10 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +                )
![images](https://github.com/user-attachments/assets/c8ada2c3-d640-4d9e-b7a0-ea31fe96463d)

2025-01-09 00:10 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/HighSpecimenParkAuto.java
> +        }
![images](https://github.com/user-attachments/assets/89b59726-9760-4afc-bff6-ec64aaa611e9)
fixed

2025-01-09 00:14 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Teleop/IntoTheDeepTeleOp.java
> +            armPosition.update(-0.008);
![images](https://github.com/user-attachments/assets/2017af88-f9a0-4453-9070-84e6b868ee23)

2025-01-09 00:15 UTC, merged